worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream lemmy {
    server lemmy:8536;
  }

  upstream lemmy-ui {
    server lemmy-ui:1234;
  }

  server {
    listen 8536;

    # لو الـ request API أو activitypub → backend
    location ~ ^/(api|pictrs|feeds|nodeinfo|.well-known|version|sitemap.xml) {
      proxy_pass http://lemmy;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # غير كده → UI
    location / {
      proxy_pass http://lemmy-ui;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
