name: Lemmy CI

on:
  push:
    branches: [dev, main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer files to the runner
        uses: actions/checkout@v4
        
      - name: Check Required Files
        run: |
          files=("docker-compose.yml" "nginx_internal.conf" "lemmy.hjson" "Dockerfile")
          for f in "${files[@]}"; do
            if [ ! -f $f ]; then
              echo "$f not exist!"
              exit 1
            fi
            done

  build-and-push:
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mahmoud755/lemmy-devops:latest
